import "./globals.css"
import { Roboto, Lobster_Two } from "next/font/google"
import Nav from "./components/Nav"
import Hydrate from "./components/Hydrate"
import Image from "next/image"
import frontgrill from "@/assets/frontpagegrill.jpg"

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
})

const lobster = Lobster_Two({
  weight: ["700"],
  subsets: ["latin"],
  variable: "--font-lobster",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

// When working with server components we can prefix with 'async'
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // Fetch the user

  return (
    <html className={`${roboto.variable} ${lobster.variable}  `} lang="en">
      <Hydrate>
        <div className="relative z-0 flex">
          <Nav />
          {children}
        </div>
      </Hydrate>
    </html>
  )
}

